export type LeadUi = {
  id: string;
  name?: string | null;
  sector?: string | null;
  verticale?: string | null;
  vertical?: string | null;
  city?: string | null;
  sourceChannel?: string | null;
  status?: string | null;
  temperature?: string | null;
  score?: number | null;
  globalScore?: number | null;
  confidenceScore?: number | null;
  tags?: string[] | null;
  notes?: string | null;
  nextActionAt?: string | Date | null;
  statusReason?: string | null;
  isArchived?: boolean | null;
  website?: string | null;
  email?: string | null;
  phone?: string | null;
  createdAt?: string | Date | null;
  updatedAt?: string | Date | null;
  weakSignals?: unknown[];
  aiOutputs?: unknown[];
  events?: unknown[];
  scores?: unknown[];
  actions?: unknown[];
};
